In [2]:
import numpy as np

In [3]:
#importing the dataset to perform analysis ans saving it into numpy array
data_file = "G:/Data Science ML AI/Data course files/Make_sense_of_census1.csv"
data = np.genfromtxt(data_file, delimiter=",",skip_header=1)
print(data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [4]:
#New record
new_record = [[50, 9, 4, 1, 0, 0, 40, 0]]
print(new_record)

[[50, 9, 4, 1, 0, 0, 40, 0]]


In [5]:
#Concatenating the new record to the existing numpy array
census = np.concatenate((data, new_record),axis=0)
print(census)
print(census.shape)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]
(1001, 8)


In [6]:
#Subsetting the array to include only 'Age' column
age = census[:,0]
print(age)

[39. 50. 38. ... 40. 39. 50.]


In [7]:
#Finding the max and min age
max_age = max(age)
min_age = min(age)
print(max_age)
print(min_age)

90.0
17.0


In [8]:
#Finding the mean age and standard deviation of age
age_mean = round(age.mean())
age_std = round(age.std())
print("The mean age of dataset is:",age_mean)
print("The standard deviation of age of dataset is:",age_std)

The mean age of dataset is: 38.0
The standard deviation of age of dataset is: 13.0


In [9]:
#Creating new subsets based on 'Race'
race_0 = census[census[:,2]==0]
race_1 = census[census[:,2]==1]
race_2 = census[census[:,2]==2]
race_3 = census[census[:,2]==3]
race_4 = census[census[:,2]==4]

#Finding the length of the above created subsets
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

#Printing the length of the above created subsets
print("Citizen count for race 0 is:",len_0)
print("Citizen count for race 1 is:",len_1)
print("Citizen count for race 2 is:",len_2)
print("Citizen count for race 3 is:",len_3)
print("Citizen count for race 4 is:",len_4)


Citizen count for race 0 is: 10
Citizen count for race 1 is: 27
Citizen count for race 2 is: 110
Citizen count for race 3 is: 6
Citizen count for race 4 is: 848


In [10]:
#Storing the different race lengths with appropriate indexes
race_list_count = [len_0,len_1,len_2,len_3,len_4]
print(race_list_count)

#Storing the race with minimum length into a variable 
minority_race = race_list_count.index(min(race_list_count))
print("The minority race is:",minority_race)

[10, 27, 110, 6, 848]
The minority race is: 3


In [11]:
#Subsetting the array based on the age to filter senior citizens
senior_citizens = census[census[:,0]>60]

#Calculating the sum of all the values of array to get working hours for senior citizens
working_hours_sum = senior_citizens.sum(axis=0)[6]
print(working_hours_sum)

#Finding the length of the senior_citizens array
senior_citizens_len = len(senior_citizens)
print("count of senior citizens is :",senior_citizens_len)




1917.0
count of senior citizens is : 61


In [12]:
#Finding the average working hours for senior citizens
avg_working_hours = round(working_hours_sum/senior_citizens_len)
print("Average working hours for senior citizens are :",avg_working_hours)

Average working hours for senior citizens are : 31.0


In [13]:
#Creating an array based on 'education' column to find high education level and low eductaion level
high = census[census[:,1]>10]
low = census[census[:,1]<=10]

print("Number of highly educated people:",len(high))
print("Number of low educated people:",len(low))

Number of highly educated people: 327
Number of low educated people: 674


In [16]:
#Finding the high average pay (finding the mean for high array from income column)
avg_pay_high = high[:,7].mean()
print("The average pay of people with high eduation is :",avg_pay_high)

#Finding the low average pay (finding the mean for low array from income column)
avg_pay_low = low[:,7].mean()
print("The average pay of people with low education is :",avg_pay_low)

The average pay of people with high eduation is : 0.42813455657492355
The average pay of people with low education is : 0.13649851632047477
